/**
 * IngestKit Node.js SDK
 *
 * After running `ingestkit generate`, you can import and use:
 *
 * const { Client } = require('./ingestkit')
 * const client = new Client()
 * await client.userSignup.send({ userId: "123", email: "user@example.com" })
 */

module.exports = {
  // The Client class will be auto-generated by `ingestkit generate`
  // This is just a placeholder for documentation
  Client: function() {
    throw new Error(
      'Client not generated yet. ' +
      'Run "npx ingestkit generate" in your project directory first.'
    );
  }
};
