package schema

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateConsumer generates consumer event routing and batch handling code
func GenerateConsumer(schema *Schema) (string, error) {
	var builder strings.Builder

	// Header
	builder.WriteString("// Code generated by IngestKit Schema Compiler. DO NOT EDIT.\n\n")
	builder.WriteString("package consumer\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"context\"\n")
	builder.WriteString("\t\"encoding/json\"\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"log\"\n\n")
	builder.WriteString("\t\"github.com/feat7/ingestkit/generated/models\"\n")
	builder.WriteString("\t\"github.com/feat7/ingestkit/generated/storage\"\n")
	builder.WriteString("\t\"github.com/feat7/ingestkit/internal/messaging\"\n")
	builder.WriteString(")\n\n")

	// Generate event handler struct
	builder.WriteString("// BatchHandler processes event batches and writes them to storage\n")
	builder.WriteString("type BatchHandler struct {\n")
	builder.WriteString("\twriter *storage.Writer\n")
	builder.WriteString("}\n\n")

	builder.WriteString("// NewBatchHandler creates a new batch handler with the given storage writer\n")
	builder.WriteString("func NewBatchHandler(writer *storage.Writer) *BatchHandler {\n")
	builder.WriteString("\treturn &BatchHandler{writer: writer}\n")
	builder.WriteString("}\n\n")

	// Get sorted event names for deterministic output
	eventNames := make([]string, 0, len(schema.Events))
	for eventName := range schema.Events {
		eventNames = append(eventNames, eventName)
	}
	sort.Strings(eventNames)

	// Generate main batch processing function
	builder.WriteString("// ProcessBatch unmarshals, groups, and writes events by type\n")
	builder.WriteString("func (h *BatchHandler) ProcessBatch(ctx context.Context, envelopes []*messaging.EventEnvelope) error {\n")
	builder.WriteString("\tlog.Printf(\"📦 Processing batch: %d events\", len(envelopes))\n\n")

	// Declare slices for each event type
	builder.WriteString("\t// Group events by type for batch insertion\n")
	for _, eventName := range eventNames {
		structName := toPascalCase(eventName)
		varName := toCamelCase(eventName) + "s"
		builder.WriteString(fmt.Sprintf("\t%s := make([]*models.%s, 0)\n", varName, structName))
	}
	builder.WriteString("\n")

	// Generate unmarshal and grouping logic
	builder.WriteString("\t// Unmarshal and group events\n")
	builder.WriteString("\tfor _, envelope := range envelopes {\n")
	builder.WriteString("\t\tswitch envelope.EventType {\n")

	for _, eventName := range eventNames {
		structName := toPascalCase(eventName)
		varName := toCamelCase(eventName) + "s"

		builder.WriteString(fmt.Sprintf("\t\tcase \"%s\":\n", eventName))
		builder.WriteString(fmt.Sprintf("\t\t\tvar event models.%s\n", structName))
		builder.WriteString("\t\t\tif err := unmarshalEvent(envelope, &event); err != nil {\n")
		builder.WriteString(fmt.Sprintf("\t\t\t\treturn fmt.Errorf(\"failed to unmarshal %s: %%w\", err)\n", eventName))
		builder.WriteString("\t\t\t}\n")
		builder.WriteString(fmt.Sprintf("\t\t\t%s = append(%s, &event)\n\n", varName, varName))
	}

	builder.WriteString("\t\tdefault:\n")
	builder.WriteString("\t\t\treturn fmt.Errorf(\"unknown event type: %s\", envelope.EventType)\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t}\n\n")

	// Generate batch write logic
	builder.WriteString("\t// Write batches to database\n")
	for _, eventName := range eventNames {
		structName := toPascalCase(eventName)
		varName := toCamelCase(eventName) + "s"

		builder.WriteString(fmt.Sprintf("\tif len(%s) > 0 {\n", varName))
		builder.WriteString(fmt.Sprintf("\t\tif err := h.writer.Write%sBatch(%s); err != nil {\n", structName, varName))
		builder.WriteString(fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to write %s batch: %%w\", err)\n", eventName))
		builder.WriteString("\t\t}\n")
		builder.WriteString(fmt.Sprintf("\t\tlog.Printf(\"✅ Wrote %%d %s events\", len(%s))\n", eventName, varName))
		builder.WriteString("\t}\n\n")
	}

	builder.WriteString("\treturn nil\n")
	builder.WriteString("}\n\n")

	// Generate unmarshalEvent helper
	builder.WriteString("// unmarshalEvent unmarshals the event envelope payload into a typed event struct\n")
	builder.WriteString("func unmarshalEvent(envelope *messaging.EventEnvelope, event interface{}) error {\n")
	builder.WriteString("\t// Unmarshal raw JSON directly into the typed event struct\n")
	builder.WriteString("\tif err := json.Unmarshal(envelope.Payload, event); err != nil {\n")
	builder.WriteString("\t\treturn fmt.Errorf(\"failed to unmarshal event: %w\", err)\n")
	builder.WriteString("\t}\n\n")

	builder.WriteString("\t// Set tenant_id from envelope\n")
	builder.WriteString("\tswitch e := event.(type) {\n")
	for _, eventName := range eventNames {
		structName := toPascalCase(eventName)
		builder.WriteString(fmt.Sprintf("\tcase *models.%s:\n", structName))
		builder.WriteString("\t\te.TenantID = envelope.TenantID\n")
	}
	builder.WriteString("\t}\n\n")

	builder.WriteString("\treturn nil\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}

// toCamelCase converts snake_case to camelCase
func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			result += strings.ToUpper(string(parts[i][0])) + parts[i][1:]
		}
	}
	return result
}
