package schema

import (
	"fmt"
	"strings"
	"unicode"
)

// GenerateGo generates Go structs for all events in the schema
func GenerateGo(schema *Schema) (string, error) {
	var builder strings.Builder

	// Header
	builder.WriteString("// Code generated by IngestKit Schema Compiler. DO NOT EDIT.\n\n")
	builder.WriteString("package models\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"encoding/json\"\n")
	builder.WriteString("\t\"time\"\n")
	builder.WriteString(")\n\n")

	// Generate struct for each event
	for eventName, event := range schema.Events {
		goStruct, err := generateEventStruct(eventName, event)
		if err != nil {
			return "", fmt.Errorf("failed to generate Go struct for event '%s': %w", eventName, err)
		}
		builder.WriteString(goStruct)
		builder.WriteString("\n\n")
	}

	return builder.String(), nil
}

// generateEventStruct generates a Go struct for a single event
func generateEventStruct(eventName string, event *Event) (string, error) {
	var builder strings.Builder

	structName := toPascalCase(eventName)

	// Struct comment
	if event.Description != "" {
		builder.WriteString(fmt.Sprintf("// %s represents: %s\n", structName, event.Description))
	} else {
		builder.WriteString(fmt.Sprintf("// %s event\n", structName))
	}

	// Struct definition
	builder.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	// Standard fields (always present)
	builder.WriteString("\tTenantID  string    `json:\"tenant_id\" validate:\"required\"`\n")
	builder.WriteString("\tEventID   int64     `json:\"event_id,omitempty\"`\n")
	builder.WriteString("\tTimestamp time.Time `json:\"timestamp,omitempty\"`\n\n")

	// Event-specific fields
	for fieldName, field := range event.Fields {
		fieldGoName := toPascalCase(fieldName)
		fieldGoType := mapFieldTypeToGo(field.Type)

		// Build tags
		jsonTag := fieldName
		validateTag := buildValidateTag(field)

		tags := fmt.Sprintf("`json:\"%s\"", jsonTag)
		if validateTag != "" {
			tags += fmt.Sprintf(" validate:\"%s\"", validateTag)
		}
		tags += "`"

		// Field comment
		if field.Description != "" {
			builder.WriteString(fmt.Sprintf("\t// %s\n", field.Description))
		}

		builder.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldGoName, fieldGoType, tags))
	}

	builder.WriteString("}")

	return builder.String(), nil
}

// toPascalCase converts snake_case to PascalCase
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(string(part[0])) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

// toSnakeCase converts PascalCase to snake_case (for reverse mapping)
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			result.WriteRune('_')
		}
		result.WriteRune(unicode.ToLower(r))
	}
	return result.String()
}

// mapFieldTypeToGo maps schema field types to Go types
func mapFieldTypeToGo(fieldType string) string {
	switch fieldType {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "decimal":
		return "float64"
	case "boolean":
		return "bool"
	case "jsonb":
		return "json.RawMessage"
	case "timestamp":
		return "time.Time"
	default:
		return "interface{}"
	}
}

// buildValidateTag builds the validate tag based on field constraints
func buildValidateTag(field *Field) string {
	var validators []string

	if field.Required {
		validators = append(validators, "required")
	}

	if len(field.Values) > 0 {
		// Enum validation
		enumValues := strings.Join(field.Values, "|")
		validators = append(validators, fmt.Sprintf("oneof=%s", enumValues))
	}

	// Type-specific validators
	switch field.Type {
	case "string":
		// Could add max length, etc.
	case "integer":
		// Could add min/max
	case "decimal":
		// Could add min/max
	}

	if len(validators) == 0 {
		return ""
	}

	return strings.Join(validators, ",")
}
