package schema

import (
	"fmt"
	"strings"
)

// GenerateSQL generates PostgreSQL DDL for all events in the schema
func GenerateSQL(schema *Schema) (string, error) {
	var builder strings.Builder

	// Header
	builder.WriteString("-- IngestKit Generated Schema\n")
	builder.WriteString(fmt.Sprintf("-- Schema Version: %s\n", schema.Version))
	builder.WriteString("-- DO NOT EDIT MANUALLY - Generated by: ingestkit schema compile\n\n")

	// Generate table for each event
	for eventName, event := range schema.Events {
		sql, err := generateEventTable(eventName, event)
		if err != nil {
			return "", fmt.Errorf("failed to generate SQL for event '%s': %w", eventName, err)
		}
		builder.WriteString(sql)
		builder.WriteString("\n\n")
	}

	return builder.String(), nil
}

// generateEventTable generates SQL DDL for a single event table
func generateEventTable(eventName string, event *Event) (string, error) {
	var builder strings.Builder

	tableName := fmt.Sprintf("events_%s", eventName)

	// Table comment
	if event.Description != "" {
		builder.WriteString(fmt.Sprintf("-- %s\n", event.Description))
	}

	// CREATE TABLE statement
	builder.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))

	// Standard columns (always present)
	builder.WriteString("    tenant_id VARCHAR(255) NOT NULL,\n")
	builder.WriteString("    event_id BIGSERIAL,\n")
	builder.WriteString("    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n")

	// Event-specific fields
	for fieldName, field := range event.Fields {
		sqlType := mapFieldTypeToSQL(field.Type)
		nullable := "NULL"
		if field.Required {
			nullable = "NOT NULL"
		}

		defaultClause := ""
		if field.Default != "" {
			defaultClause = fmt.Sprintf(" DEFAULT %s", formatDefaultValue(field.Type, field.Default))
		}

		builder.WriteString(fmt.Sprintf("    %s %s %s%s", fieldName, sqlType, nullable, defaultClause))

		// Add comment for field
		if field.Description != "" {
			builder.WriteString(fmt.Sprintf(",  -- %s", field.Description))
		}

		builder.WriteString(",\n")
	}

	// Primary key (composite: tenant_id + event_id for partitioning)
	builder.WriteString("    PRIMARY KEY (tenant_id, event_id)\n")
	builder.WriteString(") PARTITION BY LIST (tenant_id);\n\n")

	// Create indexes for indexed fields
	for fieldName, field := range event.Fields {
		if field.Indexed {
			indexName := fmt.Sprintf("idx_%s_%s", eventName, fieldName)
			builder.WriteString(fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s(%s);\n",
				indexName, tableName, fieldName))
		}
	}

	// Always create timestamp index for time-based queries
	builder.WriteString(fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_timestamp ON %s(timestamp);\n",
		eventName, tableName))

	return builder.String(), nil
}

// mapFieldTypeToSQL maps schema field types to PostgreSQL types
func mapFieldTypeToSQL(fieldType string) string {
	switch fieldType {
	case "string":
		return "VARCHAR(255)"
	case "integer":
		return "BIGINT"
	case "decimal":
		return "DECIMAL(20, 2)"
	case "boolean":
		return "BOOLEAN"
	case "jsonb":
		return "JSONB"
	case "timestamp":
		return "TIMESTAMPTZ"
	default:
		return "TEXT" // Fallback
	}
}

// formatDefaultValue formats a default value for SQL based on field type
// This prevents SQL injection by properly escaping/formatting values
func formatDefaultValue(fieldType, value string) string {
	switch fieldType {
	case "string":
		// Escape single quotes by doubling them (PostgreSQL standard)
		escaped := strings.ReplaceAll(value, "'", "''")
		return fmt.Sprintf("'%s'", escaped)
	case "integer", "decimal":
		// Numeric values should not be quoted
		// TODO: Could add validation that value is actually numeric
		return value
	case "boolean":
		// Boolean values should not be quoted
		if value == "true" || value == "false" {
			return value
		}
		// Default to false if invalid
		return "false"
	case "timestamp":
		// Timestamps should be quoted
		escaped := strings.ReplaceAll(value, "'", "''")
		return fmt.Sprintf("'%s'", escaped)
	case "jsonb":
		// JSON should be quoted
		escaped := strings.ReplaceAll(value, "'", "''")
		return fmt.Sprintf("'%s'", escaped)
	default:
		// For unknown types, quote and escape
		escaped := strings.ReplaceAll(value, "'", "''")
		return fmt.Sprintf("'%s'", escaped)
	}
}
