package schema

import (
	"fmt"
	"strings"
)

// GenerateStorage generates PostgreSQL storage writer code for all events
func GenerateStorage(schema *Schema) (string, error) {
	var builder strings.Builder

	// Header
	builder.WriteString("// Code generated by IngestKit Schema Compiler. DO NOT EDIT.\n\n")
	builder.WriteString("package storage\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"database/sql\"\n")
	builder.WriteString("\t\"encoding/json\"\n")
	builder.WriteString("\t\"fmt\"\n\n")
	builder.WriteString("\t_ \"github.com/lib/pq\"\n")
	builder.WriteString("\t\"github.com/yourusername/ingestkit/generated/models\"\n")
	builder.WriteString(")\n\n")

	// Writer struct
	builder.WriteString("// Writer handles writing events to PostgreSQL\n")
	builder.WriteString("type Writer struct {\n")
	builder.WriteString("\tdb *sql.DB\n")
	builder.WriteString("}\n\n")

	// NewWriter function
	builder.WriteString("// NewWriter creates a new PostgreSQL writer\n")
	builder.WriteString("func NewWriter(connStr string) (*Writer, error) {\n")
	builder.WriteString("\tdb, err := sql.Open(\"postgres\", connStr)\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"failed to open database: %w\", err)\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tif err := db.Ping(); err != nil {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"failed to ping database: %w\", err)\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\treturn &Writer{db: db}, nil\n")
	builder.WriteString("}\n\n")

	// Generate write method for each event
	for eventName, event := range schema.Events {
		method, err := generateWriteMethod(eventName, event)
		if err != nil {
			return "", fmt.Errorf("failed to generate write method for '%s': %w", eventName, err)
		}
		builder.WriteString(method)
		builder.WriteString("\n\n")
	}

	// Close method
	builder.WriteString("// Close closes the database connection\n")
	builder.WriteString("func (w *Writer) Close() error {\n")
	builder.WriteString("\treturn w.db.Close()\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}

func generateWriteMethod(eventName string, event *Event) (string, error) {
	var builder strings.Builder

	structName := toPascalCase(eventName)
	tableName := fmt.Sprintf("events_%s", eventName)

	// Method comment
	builder.WriteString(fmt.Sprintf("// Write%s writes a %s event to the database\n", structName, eventName))
	builder.WriteString(fmt.Sprintf("func (w *Writer) Write%s(event *models.%s) error {\n", structName, structName))

	// Collect field names for INSERT
	fieldNames := make([]string, 0, len(event.Fields))
	for fieldName := range event.Fields {
		fieldNames = append(fieldNames, fieldName)
	}

	// Handle JSONB fields - collect them first
	jsonbFields := make([]string, 0)
	for fieldName, field := range event.Fields {
		if field.Type == "jsonb" {
			jsonbFields = append(jsonbFields, fieldName)
		}
	}

	// Declare variables upfront to avoid := issues
	builder.WriteString("\tvar err error\n")
	if len(jsonbFields) > 0 {
		for _, fieldName := range jsonbFields {
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\tvar %s []byte\n", varName))
		}
	}
	builder.WriteString("\n")

	// Build column names and placeholders
	columns := []string{"tenant_id"}
	placeholders := []string{"$1"}
	paramIndex := 2

	for _, fieldName := range fieldNames {
		columns = append(columns, fieldName)
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramIndex))
		paramIndex++
	}

	// Build INSERT query
	builder.WriteString("\tquery := `\n")
	builder.WriteString(fmt.Sprintf("\t\tINSERT INTO %s (%s)\n", tableName, strings.Join(columns, ", ")))
	builder.WriteString(fmt.Sprintf("\t\tVALUES (%s)\n", strings.Join(placeholders, ", ")))
	builder.WriteString("\t`\n\n")

	if len(jsonbFields) > 0 {
		builder.WriteString("\t// Marshal JSONB fields\n")
		for _, fieldName := range jsonbFields {
			goFieldName := toPascalCase(fieldName)
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\t%s, err = json.Marshal(event.%s)\n", varName, goFieldName))
			builder.WriteString("\tif err != nil {\n")
			builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to marshal %s: %%w\", err)\n", fieldName))
			builder.WriteString("\t}\n\n")
		}
	}

	// Execute query
	builder.WriteString("\t_, err = w.db.Exec(query,\n")
	builder.WriteString("\t\tevent.TenantID,\n")

	// Add parameters in order
	for _, fieldName := range fieldNames {
		field := event.Fields[fieldName]
		goFieldName := toPascalCase(fieldName)

		if field.Type == "jsonb" {
			// Use marshaled variable
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\t\t%s,\n", varName))
		} else {
			// Use field directly
			builder.WriteString(fmt.Sprintf("\t\tevent.%s,\n", goFieldName))
		}
	}

	builder.WriteString("\t)\n\n")

	// Error handling
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to insert %s: %%w\", err)\n", eventName))
	builder.WriteString("\t}\n\n")
	builder.WriteString("\treturn nil\n")
	builder.WriteString("}")

	return builder.String(), nil
}
