package schema

import (
	"fmt"
	"strings"
)

// GenerateStorage generates PostgreSQL storage writer code for all events
func GenerateStorage(schema *Schema) (string, error) {
	var builder strings.Builder

	// Header
	builder.WriteString("// Code generated by IngestKit Schema Compiler. DO NOT EDIT.\n\n")
	builder.WriteString("package storage\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"context\"\n")
	builder.WriteString("\t\"encoding/json\"\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"time\"\n\n")
	builder.WriteString("\t\"github.com/jackc/pgx/v5\"\n")
	builder.WriteString("\t\"github.com/jackc/pgx/v5/pgxpool\"\n")
	builder.WriteString("\t\"github.com/feat7/ingestkit/generated/models\"\n")
	builder.WriteString(")\n\n")

	// Writer struct
	builder.WriteString("// Writer handles writing events to PostgreSQL using pgx connection pool\n")
	builder.WriteString("type Writer struct {\n")
	builder.WriteString("\tpool *pgxpool.Pool\n")
	builder.WriteString("}\n\n")

	// Config struct
	builder.WriteString("// Config holds database connection pool configuration\n")
	builder.WriteString("type Config struct {\n")
	builder.WriteString("\tMaxOpenConns    int           // Maximum number of open connections (default: 50)\n")
	builder.WriteString("\tMaxIdleConns    int           // Maximum number of idle connections (default: 10)\n")
	builder.WriteString("\tConnMaxLifetime time.Duration // Maximum connection lifetime (default: 1 hour)\n")
	builder.WriteString("}\n\n")

	builder.WriteString("// DefaultConfig returns the default database configuration\n")
	builder.WriteString("func DefaultConfig() *Config {\n")
	builder.WriteString("\treturn &Config{\n")
	builder.WriteString("\t\tMaxOpenConns:    50,\n")
	builder.WriteString("\t\tMaxIdleConns:    10,\n")
	builder.WriteString("\t\tConnMaxLifetime: time.Hour,\n")
	builder.WriteString("\t}\n")
	builder.WriteString("}\n\n")

	// NewWriter function
	builder.WriteString("// NewWriter creates a new PostgreSQL writer with default configuration\n")
	builder.WriteString("func NewWriter(connStr string) (*Writer, error) {\n")
	builder.WriteString("\treturn NewWriterWithConfig(connStr, DefaultConfig())\n")
	builder.WriteString("}\n\n")

	builder.WriteString("// NewWriterWithConfig creates a new PostgreSQL writer with custom configuration\n")
	builder.WriteString("func NewWriterWithConfig(connStr string, config *Config) (*Writer, error) {\n")
	builder.WriteString("\tpoolConfig, err := pgxpool.ParseConfig(connStr)\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"failed to parse connection string: %w\", err)\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\t// Configure connection pool\n")
	builder.WriteString("\tpoolConfig.MaxConns = int32(config.MaxOpenConns)\n")
	builder.WriteString("\tpoolConfig.MinConns = int32(config.MaxIdleConns)\n")
	builder.WriteString("\tpoolConfig.MaxConnLifetime = config.ConnMaxLifetime\n\n")
	builder.WriteString("\tpool, err := pgxpool.NewWithConfig(context.Background(), poolConfig)\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"failed to create connection pool: %w\", err)\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tif err := pool.Ping(context.Background()); err != nil {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"failed to ping database: %w\", err)\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\treturn &Writer{pool: pool}, nil\n")
	builder.WriteString("}\n\n")

	// Generate write methods for each event
	for eventName, event := range schema.Events {
		// Single write method
		method, err := generateWriteMethod(eventName, event)
		if err != nil {
			return "", fmt.Errorf("failed to generate write method for '%s': %w", eventName, err)
		}
		builder.WriteString(method)
		builder.WriteString("\n\n")

		// Batch write method
		batchMethod, err := generateBatchWriteMethod(eventName, event)
		if err != nil {
			return "", fmt.Errorf("failed to generate batch write method for '%s': %w", eventName, err)
		}
		builder.WriteString(batchMethod)
		builder.WriteString("\n\n")
	}

	// GetPool method for accessing the connection pool
	builder.WriteString("// GetPool returns the underlying connection pool for advanced operations\n")
	builder.WriteString("// (e.g., partition management, custom queries)\n")
	builder.WriteString("func (w *Writer) GetPool() *pgxpool.Pool {\n")
	builder.WriteString("\treturn w.pool\n")
	builder.WriteString("}\n\n")

	// Close method
	builder.WriteString("// Close closes the database connection pool\n")
	builder.WriteString("func (w *Writer) Close() error {\n")
	builder.WriteString("\tw.pool.Close()\n")
	builder.WriteString("\treturn nil\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}

func generateWriteMethod(eventName string, event *Event) (string, error) {
	var builder strings.Builder

	structName := toPascalCase(eventName)
	tableName := fmt.Sprintf("events_%s", eventName)

	// Method comment
	builder.WriteString(fmt.Sprintf("// Write%s writes a %s event to the database\n", structName, eventName))
	builder.WriteString(fmt.Sprintf("func (w *Writer) Write%s(event *models.%s) error {\n", structName, structName))
	builder.WriteString("\tctx := context.Background()\n\n")

	// Collect field names for INSERT
	fieldNames := make([]string, 0, len(event.Fields))
	for fieldName := range event.Fields {
		fieldNames = append(fieldNames, fieldName)
	}

	// Handle JSONB fields - collect them first
	jsonbFields := make([]string, 0)
	for fieldName, field := range event.Fields {
		if field.Type == "jsonb" {
			jsonbFields = append(jsonbFields, fieldName)
		}
	}

	// Build column names and placeholders
	columns := []string{"tenant_id", "timestamp"}
	placeholders := []string{"$1", "$2"}
	paramIndex := 3

	for _, fieldName := range fieldNames {
		columns = append(columns, fieldName)
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramIndex))
		paramIndex++
	}

	// Build INSERT query
	builder.WriteString("\tquery := `\n")
	builder.WriteString(fmt.Sprintf("\t\tINSERT INTO %s (%s)\n", tableName, strings.Join(columns, ", ")))
	builder.WriteString(fmt.Sprintf("\t\tVALUES (%s)\n", strings.Join(placeholders, ", ")))
	builder.WriteString("\t`\n\n")

	if len(jsonbFields) > 0 {
		builder.WriteString("\t// Marshal JSONB fields\n")
		for _, fieldName := range jsonbFields {
			goFieldName := toPascalCase(fieldName)
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\t%s, err := json.Marshal(event.%s)\n", varName, goFieldName))
			builder.WriteString("\tif err != nil {\n")
			builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to marshal %s: %%w\", err)\n", fieldName))
			builder.WriteString("\t}\n\n")
		}
	}

	// Execute query (use = if err already declared from JSONB marshaling, := otherwise)
	if len(jsonbFields) > 0 {
		builder.WriteString("\t_, err = w.pool.Exec(ctx, query,\n")
	} else {
		builder.WriteString("\t_, err := w.pool.Exec(ctx, query,\n")
	}
	builder.WriteString("\t\tevent.TenantID,\n")
	builder.WriteString("\t\tevent.Timestamp,\n")

	// Add parameters in order
	for _, fieldName := range fieldNames {
		field := event.Fields[fieldName]
		goFieldName := toPascalCase(fieldName)

		if field.Type == "jsonb" {
			// Use marshaled variable
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\t\t%s,\n", varName))
		} else {
			// Use field directly
			builder.WriteString(fmt.Sprintf("\t\tevent.%s,\n", goFieldName))
		}
	}

	builder.WriteString("\t)\n\n")

	// Error handling
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to insert %s: %%w\", err)\n", eventName))
	builder.WriteString("\t}\n\n")
	builder.WriteString("\treturn nil\n")
	builder.WriteString("}")

	return builder.String(), nil
}

func generateBatchWriteMethod(eventName string, event *Event) (string, error) {
	var builder strings.Builder

	structName := toPascalCase(eventName)
	tableName := fmt.Sprintf("events_%s", eventName)

	// Method comment
	builder.WriteString(fmt.Sprintf("// Write%sBatch writes multiple %s events to the database using COPY protocol\n", structName, eventName))
	builder.WriteString(fmt.Sprintf("func (w *Writer) Write%sBatch(events []*models.%s) error {\n", structName, structName))
	builder.WriteString("\tif len(events) == 0 {\n")
	builder.WriteString("\t\treturn nil\n")
	builder.WriteString("\t}\n\n")

	builder.WriteString("\tctx := context.Background()\n\n")

	// Collect field names for COPY
	fieldNames := make([]string, 0, len(event.Fields))
	for fieldName := range event.Fields {
		fieldNames = append(fieldNames, fieldName)
	}

	// Handle JSONB fields
	jsonbFields := make([]string, 0)
	for fieldName, field := range event.Fields {
		if field.Type == "jsonb" {
			jsonbFields = append(jsonbFields, fieldName)
		}
	}

	// Build column names for COPY
	columns := []string{"tenant_id"}
	for _, fieldName := range fieldNames {
		columns = append(columns, fieldName)
	}

	// Generate columns array
	builder.WriteString("\t// Define columns for COPY\n")
	builder.WriteString("\tcolumns := []string{")
	for i, col := range columns {
		if i > 0 {
			builder.WriteString(", ")
		}
		builder.WriteString(fmt.Sprintf("\"%s\"", col))
	}
	builder.WriteString("}\n\n")

	// Use CopyFrom (always use := because JSONB marshaling is inside the closure)
	builder.WriteString("\t// Use CopyFrom for maximum performance (uses PostgreSQL COPY protocol)\n")
	builder.WriteString("\t_, err := w.pool.CopyFrom(\n")
	builder.WriteString("\t\tctx,\n")
	builder.WriteString(fmt.Sprintf("\t\tpgx.Identifier{\"%s\"},\n", tableName))
	builder.WriteString("\t\tcolumns,\n")
	builder.WriteString("\t\tpgx.CopyFromSlice(len(events), func(i int) ([]interface{}, error) {\n")
	builder.WriteString("\t\t\tevent := events[i]\n\n")

	// Marshal JSONB fields
	if len(jsonbFields) > 0 {
		builder.WriteString("\t\t\t// Marshal JSONB field")
		if len(jsonbFields) > 1 {
			builder.WriteString("s")
		}
		builder.WriteString("\n")
		for _, fieldName := range jsonbFields {
			goFieldName := toPascalCase(fieldName)
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\t\t\t%s, err := json.Marshal(event.%s)\n", varName, goFieldName))
			builder.WriteString("\t\t\tif err != nil {\n")
			builder.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"failed to marshal %s for event %%d: %%w\", i, err)\n", fieldName))
			builder.WriteString("\t\t\t}\n\n")
		}
	}

	// Return row data
	builder.WriteString("\t\t\treturn []interface{}{\n")
	builder.WriteString("\t\t\t\tevent.TenantID,\n")
	for _, fieldName := range fieldNames {
		field := event.Fields[fieldName]
		goFieldName := toPascalCase(fieldName)

		if field.Type == "jsonb" {
			varName := fmt.Sprintf("%sJSON", fieldName)
			builder.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", varName))
		} else {
			builder.WriteString(fmt.Sprintf("\t\t\t\tevent.%s,\n", goFieldName))
		}
	}
	builder.WriteString("\t\t\t}, nil\n")
	builder.WriteString("\t\t}),\n")
	builder.WriteString("\t)\n\n")

	// Error handling
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to COPY %s batch (%%d events): %%w\", len(events), err)\n", eventName))
	builder.WriteString("\t}\n\n")
	builder.WriteString("\treturn nil\n")
	builder.WriteString("}")

	return builder.String(), nil
}
